### ISSUE TITLE
Choose menu selection tool via env var

### ISSUE THREAD

**Issue by devgioele** [thingsiplay/emojipick#2]
Because there are many alternatives to dmenu and rofi is not the only one, it would be great if any dmenu-compatible tool could be specified using an environment variable like `MENU_SELECTOR=rofi`.

**Comment by thingsiplay** [comment]
I am all for such settings, but the problem would be the options used in the script to call those programs. Even the dmenu option in Rofi to emulate dmenu needs some special care. So such a menu selector would only work, if the program options are 100% compatible to dmenu/rofi. Does any such alternative exist?

In case you are interested into, I rewrote  this in Python with much more options (including alternative menus such as rofi, dmenu and commandline fzf and even more ways). It also comes with commandline options to use alternative program nameds `--rofi CMD` in example: https://github.com/thingsiplay/emojicherrypick

**Comment by thingsiplay** [comment]
I have added the environmental variable `EMOJIPICK_CMD`, which can be used to set an alternative path or entire command with options. It still needs to be compatible to rofi or dmenu and therefore quite limited. Here are two examples setting the env variable and running the script:

    $ EMOJIPICK_CMD='rofi -dmenu' ./emojipick
    
    $ EMOJIPICK_CMD='dmenu -fn' ./emojipick

The `-fn` in for dmenu is still required, in case you want do some custom options.
