### ISSUE TITLE
change the word "dmenu"

### ISSUE THREAD

**Issue by Kaladii** [thingsiplay/emojipick#3]
Is it possible to change the word "dmenu" to "emojis" in rofi??
![image of rofi](https://user-images.githubusercontent.com/94393888/207806871-1514546c-3354-4943-b017-4e5203293a33.png)

**Comment by thingsiplay** [comment]
There is no option for in the script, but you can add `-p emojis` as an option to the line with rofi at:

    dmenu_app=${EMOJIPICK_CMD:-'rofi -dmenu -l 15 -font'}

to

    dmenu_app=${EMOJIPICK_CMD:-'rofi -dmenu -p emoji -l 15 -font'}

Sidenote: I also rewrote the entire script in pure Python instead mix of Python and Bash. It has ton of options if you want look at the new version: https://github.com/thingsiplay/emojicherrypick

**Comment by Kaladii** [comment]
tysm!
